# Generated by Django 5.1.15 on 2026-02-28 04:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=80)),
                ('open_time', models.TimeField(default='09:00')),
                ('close_time', models.TimeField(default='17:00')),
                ('slot_minutes', models.PositiveIntegerField(default=60)),
                ('max_total_dogs_per_slot', models.PositiveIntegerField(default=30)),
                ('max_large_dogs_per_slot', models.PositiveIntegerField(default=10)),
                ('max_dogs_per_owner', models.PositiveIntegerField(default=3)),
                ('allow_restricted_breeds', models.BooleanField(default=False)),
                ('checkin_open_minutes_before', models.PositiveIntegerField(default=30)),
                ('checkin_close_minutes_after_start', models.PositiveIntegerField(default=30)),
                ('cancellation_refund_hours', models.PositiveIntegerField(default=24)),
                ('max_no_show_before_suspension', models.PositiveIntegerField(default=2)),
                ('suspension_days', models.PositiveIntegerField(default=14)),
                ('base_fee_per_dog', models.DecimalField(decimal_places=2, default=Decimal('1500.00'), max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('party_size', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending_payment', '決済待ち'), ('confirmed', '予約確定'), ('checked_in', 'チェックイン済み'), ('completed', '利用完了'), ('cancelled', 'キャンセル'), ('no_show', '無断キャンセル')], default='pending_payment', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', '未決済'), ('paid', '決済済み'), ('refunded', '返金済み'), ('failed', '決済失敗')], default='unpaid', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('qr_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('no_show_marked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-start_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoShowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_show_records', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='no_show_record', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationDog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=80)),
                ('breed', models.CharField(max_length=120)),
                ('size_category', models.CharField(max_length=10)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_links', to='dogs.dog')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_dogs', to='reservations.reservation')),
            ],
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date', 'start_time'], name='reservation_date_19f2ce_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='reservation_status_f1a03a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reservationdog',
            unique_together={('reservation', 'dog')},
        ),
    ]
