# Generated by Django 5.1.15 on 2026-02-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityrule',
            name='auto_checkout_grace_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='facilityrule',
            name='max_small_dogs_per_slot',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='facilityrule',
            name='rain_closure_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='qr_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending_payment', '決済待ち'), ('confirmed', '予約確定'), ('checked_in', 'チェックイン済み'), ('completed', '利用完了'), ('cancelled', 'キャンセル'), ('no_show', '無断キャンセル'), ('expired', '期限切れ')], default='pending_payment', max_length=20),
        ),
    ]
