# Generated by Django 5.1.15 on 2026-03-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreedDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('breed', models.CharField(max_length=120)),
                ('total_checkins', models.IntegerField(default=0)),
                ('unique_dogs', models.IntegerField(default=0)),
                ('total_duration_minutes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-total_checkins', 'breed'],
                'indexes': [models.Index(fields=['date'], name='stats_breed_date_1e6e76_idx'), models.Index(fields=['breed'], name='stats_breed_breed_f039ce_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'breed'), name='uniq_breed_daily_stats_date_breed')],
            },
        ),
    ]
