# Generated by Django 5.1.15 on 2026-03-01 05:41

import django.utils.timezone
from django.db import migrations


def backfill_membership(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Membership = apps.get_model("accounts", "Membership")

    existing_user_ids = set(Membership.objects.values_list("user_id", flat=True))
    new_rows = []
    for user_id in User.objects.exclude(id__in=existing_user_ids).values_list("id", flat=True):
        new_rows.append(
            Membership(
                user_id=user_id,
                tier="regular",
                joined_at=django.utils.timezone.localdate(),
            )
        )

    if new_rows:
        Membership.objects.bulk_create(new_rows)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_membership'),
    ]

    operations = [
        migrations.RunPython(backfill_membership, migrations.RunPython.noop),
    ]
