# Generated by Django 5.1.15 on 2026-03-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinlog',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
