# Generated by Django 5.1.15 on 2026-03-01 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_checkinlog_duration_minutes'),
        ('dogs', '0005_backfill_vaccine_approval'),
        ('reservations', '0002_facilityrule_auto_checkout_grace_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name_snapshot', models.CharField(max_length=80)),
                ('breed_snapshot', models.CharField(max_length=120)),
                ('size_category_snapshot', models.CharField(max_length=10)),
                ('weight_kg_snapshot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('checked_in_at', models.DateTimeField()),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in', '入場中'), ('out', '退場済み'), ('invalid', '無効')], default='in', max_length=10)),
                ('source', models.CharField(default='qr', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='dogs.dog')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='reservations.reservation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_in_at', '-id'],
                'indexes': [models.Index(fields=['status'], name='checkins_en_status_c01c8c_idx'), models.Index(fields=['checked_in_at'], name='checkins_en_checked_ba9dd6_idx'), models.Index(fields=['reservation'], name='checkins_en_reserva_1e4d49_idx'), models.Index(fields=['dog'], name='checkins_en_dog_id_288456_idx')],
            },
        ),
    ]
