# Generated by Django 5.1.15 on 2026-03-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='breed_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'オス'), ('female', 'メス'), ('unknown', '不明')], max_length=10, null=True),
        ),
    ]
