# Generated by Django 5.1.15 on 2026-03-01 06:26

from django.db import migrations


def reactivate_dogs(apps, schema_editor):
    Dog = apps.get_model("dogs", "Dog")
    Dog.objects.filter(is_active=False).update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_dog_breed_group_dog_gender'),
    ]

    operations = [
        migrations.RunPython(reactivate_dogs, migrations.RunPython.noop),
    ]
