# Generated by Django 5.1.15 on 2026-03-01 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_reactivate_dogs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='vaccine_approval_status',
            field=models.CharField(choices=[('pending', '確認待ち'), ('approved', '承認済み'), ('rejected', '差し戻し')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='dog',
            name='vaccine_review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='vaccine_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='vaccine_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vaccine_dogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
