# Generated by Django 5.1.15 on 2026-03-01 06:45

from django.db import migrations


def backfill_vaccine_approval(apps, schema_editor):
    Dog = apps.get_model("dogs", "Dog")
    Dog.objects.filter(vaccine_approval_status="pending").update(vaccine_approval_status="approved")


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_dog_vaccine_approval_status_dog_vaccine_review_note_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_vaccine_approval, migrations.RunPython.noop),
    ]
