# Generated by Django 5.1.15 on 2026-06-10 15:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0006_dog_breed_normalization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))]),
        ),
    ]
